# Site settings
baseurl = "/"
languageCode = "en"
title = "bits and pieces"
theme = "hemingway2"

keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/davidsanwald"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/davidsanwald"
fa_icon = "fa-twitter"


[[params.social]]
url = "https://telegram.me/likesfoxes"
fa_icon = "fa-telegram"

[[params.social]]
url = "https://medium.com/@davidsanwald"
fa_icon = "fa-medium"

[[params.social]]
url = "https://www.linkedin.com/in/david-sanwald-98249994"
fa_icon = "fa-linkedin"

